
os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: 
  - xcode7.3
  - xcode8
  - xcode8.1
  - xcode8.2
  - xcode8.3
  - xcode9
script:
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change
