matrix:
  include:   
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode7.3
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode8
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode8.1  
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode8.2
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode8.3
    - os: osx
      dist: trusty
      sudo: required
      osx_image: xcode9
language: generic
script:
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change
